### ISSUE TITLE
Hava a singleton it is an antipattern nowadays, adding a lite instance

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/JRPClightning#63]
When I start this project I taken some decisions that today I will never take again, some of them are:

- Use a singleton instance, this break the possibility to use DI library with the class
- Create the java version of each command, (I should be used the reflection to make the job)
- Divided the library into two modules, one is the RPC module with all the RPC calls and JSON calls, and the other one is the plugin module and will create an internal instance of the RPC class.
- Avoid mixing the structured class with a generic method like `rawCall`, I would like to have a different class, like LiteCLightningRpc(rpc_path), and ClightninRPC(rpc_path).

I would like to implement some of these changes, like
- [ ] `LiteClightningRpc(rpc_path) `as first, that implements an interface like the [lite-bitcoin-rpc](https://github.com/clightning4j/lite-bitcoin-rpc). Deadline version 0.2.3 https://github.com/clightning4j/JRPClightning/issues/62
- [ ] Remove the singleton instance from the library, deadline version 0.3.0 https://github.com/clightning4j/JRPClightning/issues/60
- [ ] Divide the project into submodule to support also Android, deadline unsettled https://github.com/clightning4j/JRPClightning/issues/61
